export const nameMap = {
    '/login': 'Login',
    '/dashboard': 'Dashboard',
    '/dashboard/manage-product': 'Manage Product',
    '/dashboard/manage-product/add': 'Add Product',
    '/dashboard/manage-product/edit': 'Edit Product',
    '/dashboard/manage-article': 'Manage Article',
    '/dashboard/manage-article/add': 'Add Article',
    '/dashboard/manage-article/edit': 'Edit Article',
    '/dashboard/manage-admin': 'Manage Admin',
    '/dashboard/manage-admin/add': 'Add Admin',
    '/dashboard/manage-admin/edit': 'Edit Admin',
    '/dashboard/manage-event': 'Manage Event',
    '/dashboard/manage-event/add': 'Add Event',
    '/dashboard/manage-event/edit': 'Edit Event',
  };